cambios maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -42,18 +42,29 @@ jobs:
     - name: Install doxygen dependecies
       run: sudo apt-get install -y doxygen
 
+    - name: Generate Doxyfile
+      run: |
+        mkdir -p target/site/doxygen
+        doxygen -g target/site/doxygen/Doxyfile
+
     - name: Configure Doxyfile
       run: |
-        sed -i 's|^OUTPUT_DIRECTORY.*|OUTPUT_DIRECTORY       = docs/doxygen|' Doxyfile
-        sed -i 's|^GENERATE_HTML.*|GENERATE_HTML          = YES|' Doxyfile
-        sed -i 's|^HTML_OUTPUT.*|HTML_OUTPUT            = html|' Doxyfile
-        sed -i 's|^INPUT.*|INPUT                  = src/main/java|' Doxyfile
-        sed -i 's|^RECURSIVE.*|RECURSIVE              = YES|' Doxyfile
+        sed -i 's|OUTPUT_DIRECTORY       =|OUTPUT_DIRECTORY       = target/doxygen|' target/site/doxygen/Doxyfile
+        sed -i 's|GENERATE_HTML          = NO|GENERATE_HTML          = YES|' target/site/doxygen/Doxyfile
+        sed -i 's|HTML_OUTPUT            = html|HTML_OUTPUT            = html|' target/site/doxygen/Doxyfile
+        sed -i 's|INPUT                  =|INPUT                  = src/main/java|' target/site/doxygen/Doxyfile
+        sed -i 's|RECURSIVE              = NO|RECURSIVE              = YES|' target/site/doxygen/Doxyfile
+
+    - name: Check Doxyfile
+      run: ls -la target/doxygen/Doxyfile || echo "Doxyfile not found"
 
     - name: Generate Doxygen documentation
-      run: doxygen Doxyfile
+      run: doxygen target/doxygen/Doxyfile
+
+    - name: List generated HTML
+      run: ls -la target/site/doxygen
 
     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
-        folder: docs/doxygen
+        folder: target/site/doxygen
